name: terraform-plan

on:
  pull_request:
    paths:
      - 'terraform/**'
      - 'workflows/terraform-plan.yml'
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}"

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -input=false -no-color -out=tfplan-${{ github.sha }}.bin | tee plan.txt

      - name: Capture plan summary
        id: plan_summary
        run: |
          echo "summary<<'EOF'" >> "$GITHUB_OUTPUT"
          tail -n 150 plan.txt >> "$GITHUB_OUTPUT"
          echo 'EOF' >> "$GITHUB_OUTPUT"

      - name: Upload plan binary
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: terraform/tfplan-${{ github.sha }}.bin
          retention-days: 5

      - name: Upload plan details
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}-text
          path: terraform/plan.txt
          retention-days: 5

      - name: Comment plan summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const summary = `Terraform plan completed for **${{ github.head_ref }}**\n\n\`\`\`\n${{ steps.plan_summary.outputs.summary }}\n\`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
