name: terraform-apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'workflows/terraform-apply.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: Terraform workspace/environment to apply
        required: true
        default: production
      auto_approve:
        description: Apply without manual confirmation
        type: boolean
        default: false

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment || 'production' }}
    if: github.event_name == 'push' || github.event.inputs.auto_approve == 'true'
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Select workspace
        run: |
          terraform workspace list || terraform workspace new default
          terraform workspace select "${{ github.event.inputs.environment || vars.DEFAULT_TF_WORKSPACE || 'production' }}" || terraform workspace new "${{ github.event.inputs.environment || vars.DEFAULT_TF_WORKSPACE || 'production' }}"

      - name: Terraform init
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}"

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan (safety)
        run: terraform plan -input=false -no-color -out=tfplan.bin | tee plan.txt

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve tfplan.bin

      - name: Archive apply artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-${{ github.sha }}
          path: |
            terraform/plan.txt
            terraform/tfplan.bin
          retention-days: 7

      - name: Notify success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": "Terraform apply succeeded for commit ${{ github.sha }} in environment ${{ github.event.inputs.environment || 'production' }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "text": "Terraform apply failed for commit ${{ github.sha }} in environment ${{ github.event.inputs.environment || 'production' }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
